project: blackjack-server
services:
  - name: blackjack-server
    startCommand: "node server.ts"
    buildCommand: "npm install"
    healthCheckPath: "/"
    port: 4000
    environment:
      NODE_ENV: "production"
      PORT: 4000
